name: antalya_kart_redesign
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/ic/
    - assets/announcements/

  fonts:
    - family: Trenda
      fonts:
        - asset: assets/fonts/TrendaThin.otf
          weight: 100
        - asset: assets/fonts/TrendaRegular.otf
          weight: 400
        - asset: assets/fonts/TrendaSemibold.otf
          weight: 600
        - asset: assets/fonts/TrendaBold.otf
          weight: 700